'use strict';

const express = require('express');
const fs = require('fs');
const path = require('path');
const pino = require('pino');
const client = require('prom-client');
const { isEnabled, features } = require('./featureFlags');

const SERVICE_NAME = process.env.SERVICE_NAME || 'devops-midterm';
const ACTIVE_ENV = process.env.APP_ENV || 'production';

// ---------------------------------------------------------------------------
// Structured JSON logging (pino) — carried over from the Observability lab.
//
// Every log line is a single JSON object on stdout with the fields:
//   timestamp, level, service, method, path, statusCode, message
// Docker's gelf logging driver ships each stdout line to Logstash -> ELK.
// Logging is silenced under tests to keep Jest output clean.
// ---------------------------------------------------------------------------
const logger = pino({
  level: process.env.NODE_ENV === 'test' ? 'silent' : process.env.LOG_LEVEL || 'info',
  base: { service: SERVICE_NAME },
  messageKey: 'message',
  timestamp: () => `,"timestamp":"${new Date().toISOString()}"`,
  formatters: {
    level(label) {
      return { level: label };
    },
  },
});

// ---------------------------------------------------------------------------
// Prometheus metrics (prom-client) — carried over from the Observability lab.
// ---------------------------------------------------------------------------
const register = new client.Registry();
register.setDefaultLabels({ service: SERVICE_NAME });
client.collectDefaultMetrics({ register });

const requestsTotal = new client.Counter({
  name: 'app_requests_total',
  help: 'Total number of HTTP requests received by the application',
  labelNames: ['method', 'path', 'status_code'],
  registers: [register],
});

const errorsTotal = new client.Counter({
  name: 'app_errors_total',
  help: 'Total number of errors generated by the application',
  labelNames: ['path'],
  registers: [register],
});

const httpRequestDuration = new client.Histogram({
  name: 'app_request_duration_seconds',
  help: 'HTTP request latency in seconds',
  labelNames: ['method', 'path', 'status_code'],
  buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
  registers: [register],
});

const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ---------------------------------------------------------------------------
// Observability middleware: time every request, count it, and log it as JSON.
// ---------------------------------------------------------------------------
app.use((req, res, next) => {
  const endTimer = httpRequestDuration.startTimer();
  res.on('finish', () => {
    const labels = {
      method: req.method,
      path: req.path,
      status_code: res.statusCode,
    };
    requestsTotal.inc(labels);
    endTimer(labels);

    const level =
      res.statusCode >= 500 ? 'error' : res.statusCode >= 400 ? 'warn' : 'info';
    logger[level](
      {
        method: req.method,
        path: req.originalUrl,
        statusCode: res.statusCode,
      },
      'request handled'
    );
  });
  next();
});

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

// Homepage — feature-flagged UI (Feature Flag strategy from Assignment 1).
app.get('/', (req, res) => {
  const newUI = isEnabled(features.NEW_UI);
  if (newUI) {
    res.send(`
        <html>
            <head><title>DevOps Final — Modern Dashboard</title>
            <style>
              body { font-family: sans-serif; background:#121212; color:#fff; display:flex; align-items:center; justify-content:center; height:100vh; margin:0; }
              .card { background:#1e1e1e; padding:2rem; border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.5); text-align:center; border:1px solid #333; max-width:520px; }
              h1 { color:#bb86fc; }
              .badge { background:#03dac6; color:#000; padding:4px 8px; border-radius:4px; font-size:0.8rem; font-weight:bold; }
              form { margin-top:1rem; }
              input,button { padding:8px; border-radius:6px; border:1px solid #444; }
              button { background:#bb86fc; color:#000; font-weight:bold; cursor:pointer; }
            </style>
            </head>
            <body>
                <div class="card">
                    <h1>Modern Dashboard <span class="badge">NEW UI</span></h1>
                    <p>Active environment: <strong>${ACTIVE_ENV}</strong></p>
                    <p>Feature flag <code>NEW_UI_ENABLED</code> is ON.</p>
                    <form action="/submit" method="POST">
                        <input type="text" name="data" placeholder="Enter some data" required />
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </body>
        </html>
    `);
  } else {
    res.send(`
        <html>
            <head><title>DevOps Final App</title></head>
            <body style="font-family: Arial, sans-serif; text-align: center; margin-top: 50px;">
                <h1>Welcome to the DevOps Final Blue-Green App!</h1>
                <p>Active environment: <strong>${ACTIVE_ENV}</strong></p>
                <p>Standard UI — set <code>NEW_UI_ENABLED=true</code> to enable the modern dashboard.</p>
                <form action="/submit" method="POST">
                    <input type="text" name="data" placeholder="Enter some data" required />
                    <button type="submit">Submit</button>
                </form>
            </body>
        </html>
    `);
  }
});

// Dynamic route — greets the user by name.
app.get('/user/:name', (req, res) => {
  const name = req.params.name;
  res.status(200).json({ message: `Hello, ${name}!` });
});

// Logs view — surface the health-monitor log in the browser.
app.get('/logs', (req, res) => {
  const logPath = path.join(__dirname, 'logs', 'health.log');
  if (fs.existsSync(logPath)) {
    res.type('text/plain').send(fs.readFileSync(logPath, 'utf8'));
  } else {
    res.send('No logs found.');
  }
});

// Input form endpoint — processes and echoes submitted data.
app.post('/submit', (req, res) => {
  const { data } = req.body;
  if (!data) {
    return res.status(400).json({ error: 'Data is required' });
  }
  res.status(201).json({ message: 'Data received', received: data });
});

// Health check endpoint for monitoring & container health probes.
app.get('/health', (req, res) => {
  res.status(200).json({
    status: 'ok',
    service: SERVICE_NAME,
    env: ACTIVE_ENV,
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  });
});

// Deliberate failure — drives the error rate up for the alerting demo.
app.get('/error', (req, res) => {
  errorsTotal.inc({ path: '/error' });
  res.status(500).json({ error: 'Simulated application error' });
});

// Prometheus scrape endpoint.
app.get('/metrics', async (req, res) => {
  res.set('Content-Type', register.contentType);
  res.end(await register.metrics());
});

// ---------------------------------------------------------------------------
// Catch-all error handler — also counts unexpected failures as app errors.
// ---------------------------------------------------------------------------
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  errorsTotal.inc({ path: req.path });
  logger.error(
    {
      method: req.method,
      path: req.originalUrl,
      statusCode: 500,
      message: err.message,
    },
    'unhandled application error'
  );
  res.status(500).json({ error: 'Internal Server Error' });
});

module.exports = app;
module.exports.logger = logger;
